### ISSUE TITLE
Timeout with mjai client. and Restarting game.

### ISSUE THREAD

**Issue by specialkkk** [tomohxx/mjai-gateway#1]
Could you please implement the Timeout with mjai client. and Restarting game. for your project? 

Thank you so much for your help!

**Comment by specialkkk** [comment]
elif tag == 'REINIT':
            # recv: {"tag":"GO","type":"25","lobby":"1717","gpid":"967297C0-57844F69"}
            # recv: {"tag":"UN","n0":"%4E%6F%4E%61%6D%65","n1":"%4E%6F%4E%61%6D%65","n2":"","n3":"%E7%8B%97%E7%8C%AB","dan":"0,0,0,2","rate":"1500.00,1500.00,1500.00,1502.64","sx":"M,M,C,M"}
            # recv: {"tag":"SAIKAI","ba":"0,0","oya":"3","sc":"350,0,350,0,0,0,350,0"}
            # recv: {"tag":"REINIT","seed":"0,0,0,0,5,72","ten":"350,350,0,350","oya":"3","hai":"33,37,43,59,68,80,93,95,102,116,119,128,135","m1":"31520,30752","kawa0":"41,79,89","kawa1":"64,32,67","kawa3":"112,34,131,38"}
            message['tag'] = 'INIT'
            self.decodeAndDisplay(message)
            info = self.gameInfo.kyokuInfo
            for i in range(4):
                if 'kawa' + str(i) in message:
                    river = message['kawa' + str(i)].split(',')
                    rot = False
                    for tilestr in river:
                        info.remaining -= 1 
                        if tilestr == '255':
                            rot = True
                            info.reached[i] = True
                            continue
                        if rot:
                            discardInfo = 4
                        else:
                            discardInfo = 0
                        info.rivers[i].append([int(tilestr), discardInfo])
                        info.reveal_tile(int(tilestr))
                        rot = False
                    if rot:
                        self.gameInfo.gameControlInfo.rotateNextTile[i] = True
                if 'm' + str(i) in message:
                    furostrs = message['m' + str(i)].split(',')
                    for furostr in furostrs:
                        furo = utils.decodeFuro(int(furostr))
                        info.furos[i].insert(0, furo)
                        for tilecode in furo.tilecodes:
                            info.reveal_tile(tilecode)
                        info.rivers[utils.relativeToAbsolute(furo.fromWhoRelative, i)].insert(0, [furo.tilecodes[furo.whichTileIsClaimed], 2])
                        if not furo.isKita:
                            info.hands[i] = info.hands[i][:-3]
                        if furo.isKita or furo.isKan:
                            info.remaining -= 1
            self.popUpWindow = None

**Comment by tomohxx** [comment]
Hi specialkkk!
Sorry, what is the code above?
And it would be helpful if you could make it a code block.

**Comment by specialkkk** [comment]
the copy from others ,and i want to know how to implement the Timeout with mjai client. and Restarting game. for your project?

**Comment by tomohxx** [comment]
Do the following:
Add a class to `src/responder.py` that handles the REINIT tag.
Then add an instance of that class to the processes list in `src/router.py`.

**Comment by specialkkk** [comment]
Thank you for your answer, could you implement it? I would like to refer to it. Thank you.

**Comment by tomohxx** [comment]
Sorry, that's not possible, the mjai protocol doesn't have a reconnect feature.

**Comment by lqgl** [comment]
The mjai protocol doesn't have a reconnect feature, my idea is to reconstruct the mjai events with a REINIT message and then get the last reaction for reconnect, do you think it's feasible? If yes, could you implement it?
